MODEL:
  TYPE: rpn
  CONV_BODY: ResNet.add_ResNet50_conv4_body
  NUM_CLASSES: 21
  RPN_ONLY: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 90000
  STEPS: [0, 60000, 80000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
TRAIN:
  WEIGHTS: ./model/pretrain_model/R-50.pkl
  DATASETS: ('voc_2007_train', 'voc_2007_val' )
  SCALES: (600,)
  MAX_SIZE: 1000
TEST:
  DATASETS: ('voc_2007_test',)
  SCALE: 600
  MAX_SIZE: 1000
USE_NCCL: False
OUTPUT_DIR: .
